### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by Layiid** [DexterLabZ/syrius-extension#12]
I get this error when I try to log in, I made sure it's the correct password.

<img width="393" alt="image" src="https://user-images.githubusercontent.com/111152907/184436268-8c955d7a-1a14-4453-84e2-eb6317fa60e1.png">

**Comment by Layiid** [comment]
MacOS 12.3
Google Chrome Version 104.0.5112.79

Console message: WebSocket connection to 'ws://127.0.0.1:35998/' failed:       popup.bundle.js:96

**Comment by uluCthulhu** [comment]
The problem was that you didn't enter a valid node URL to connect to. "ws://127.0.0.1:35998" is only the localhost. hence, the error. It's fixed now as there is a flow before the login and a button for changing node URL
