### ISSUE TITLE
Reference test sites to test the wallet

### ISSUE THREAD

**Issue by 0x3639** [DexterLabZ/syrius-extension#7]
Do you have any reference / test sites where we can test the functionality of the wallet?

**Comment by uluCthulhu** [comment]
What functionality do you specifically mean? You can test the extension directly in the browser and do import, generate, send/receive, stake, delegate, fuse.

**Comment by zenon-info** [comment]
I was wondering how we can test this?

`const listenToExtension = function() {
  window.addEventListener("message", (event) => {
    console.log("Message received on site ", event);
    try{
      const parsedData = event.data;
      if(parsedData.method){
        switch(parsedData.method){
          case "znn.grantedWalletRead":{
            const result = JSON.stringify(parsedData.data);
            break;
          }
          case "znn.signedTransaction": {
            const result = JSON.stringify(parsedData.data);
            break;
          }
          case "znn.znn.accountBlockSent": {
            const result = JSON.stringify(parsedData.data);
            break;
          }
        }
      }
    }
    catch(err){
      console.error(err);
    }
  });
}

const connectExtensionWallet = function() {
  window.postMessage({
    method: "znn.requestWalletAccess",
    params: {}
  }, "*");
}

const sendTransactionToSigning = function() {
  window.postMessage({
    method: "znn.sendTransactionToSigning",
    params: {
      from: 'z1qqjnwjjpnue8xmmpanz6csze6tcmtzzdtfsww7', 
      to: 'z1qqjnwjjpnue8xmmpanz6csze6tcmtzzdtfsww7', 
      amount: '330000000', // 1 ZNN = 100000000
      tokenStandard:
        'zts1znnxxxxxxxxxxxxx9z4ulx', 
      chainId: '3',   
    }
  }, "*");
}

const sendAccountBlockToSend = function() {
  window.postMessage({
    method: "znn.sendAccountBlockToSend",
    params: accountBlockTransactionExample
  }, "*");
}`
